config/routes.rb
Rails.application.routes.draw do

  get 'batches/:id/toggle' => 'batches#toggle', as: "batch_toggle"

  get 'apply/:batch/:block' => 'apply#block', as: "apply"
  get 'apply/:block/:application/up' => 'apply#up', as: "up"
  get 'apply/:block/:application/down' => 'apply#down', as: "down"
  get 'apply/summary', as: "summary"

  get 'public/index' => 'public#index'
  get 'public/students/idle' => 'public#idle_students', as: "idle_students"
  get 'public/applications/incomplete' => 'public#incomplete_applications', as: "incomplete_applications"
  get 'public/courses/available' => 'public#available_courses', as: "available_courses"
  get 'public/batches' => 'public#batches', as: "batches"
  get 'public/results' => 'public#results', as: "results"

  root to: 'public#index'

  devise_for :users, :skip => :registrations

  mount Upmin::Engine => '/admin'

  Upmin::Engine.routes.draw do
    resources :upload, only:[:create, :show]
    get "/downolad/applications" => "download#applications", as: "download_applications"
    get "/downolad/users" => "download#users", as: "download_users"
    get "/downolad/courses" => "download#courses", as: "download_courses"
    get "/upload/new/:type" => "upload#new", as: "new_upload"
  end

end

app/controllers/apply_controller.rb
class ApplyController < ApplicationController

  before_filter :authenticate_user!

  def block
    #find batch
    @batch = current_user.course_batch
    #find block
    if params[:block]
      @block = Block.find(params[:block])
      #check if block closed
      # flash[:alert] = "Block is closed." unless @block.open_status
    else
      @block = @course_batch.blocks.first
    end

    @applications = current_user.applications_for_block(@block)

    unless (@block == @batch.blocks.last) && (@batch.blocks.count > 1)
      @next_block = @batch.blocks[@batch.blocks.index(@block)+1]
    end

  end

  def up
    #block & batch & apps
    block = Block.find(params[:block])
    batch = current_user.course_batch
    applications = current_user.applications_for_block(block)
    #move application up
    application1 = Application.find(params[:application])
    application2 = applications[applications.index(application1) - 1]
    current_user.switch_applications(application1, application2)
    redirect_to apply_path(batch.id, block.id)
  end

  def down
    #block & batch & apps
    block = Block.find(params[:block])
    batch = current_user.course_batch
    applications = current_user.applications_for_block(block)
    #move application up
    application1 = Application.find(params[:application])
    application2 = applications[applications.index(application1) + 1]
    current_user.switch_applications(application1, application2)
    redirect_to apply_path(batch.id, block.id)
  end

  def summary
  end

end

app/helpers/apply_helper.rb
module ApplyHelper
end

app/views/apply/_application.html.haml
%li.list-group-item.text-center{id:"application-#{application.id}-#{application.priority}"}
  = application.course.name
  - unless @applications.index(application) == 0
    = link_to up_path(@block,application.id), class:"btn btn-default ", id:"up-#{application.id}" do
      %span.glyphicon.glyphicon-circle-arrow-up
  - unless @applications.index(application) == @applications.count-1
    = link_to down_path(@block,application.id), class:"btn btn-default ", id:"down-#{application.id}" do
      %span.glyphicon.glyphicon-circle-arrow-down

app/views/apply/block.html.haml
.container
  .row
    .col-md-12
      %h3
        = @block.name + " (#{@block.from.strftime("%H:%M")} - #{@block.to.strftime("%H:%M")})"
      - unless @block.open_status
        .alert.alert-danger
          This block is closed.
      - else
        %ul.list-group
        - @applications.each do |application|
          = render partial: "application", object: application
      %hr
      - unless @next_block.nil?
        = link_to "Next block",  apply_path(@batch.id, @next_block), class: "btn btn-primary"
      - else
        = link_to "Summary",  summary_path, class: "btn btn-info"

app/views/apply/summary.html.haml
.container
  .row
    .col-md-12
      %h3
        Course preferences summary
      %table.table
        %thead
          %tr
            %th
              Block
            %th
              Course
            %th
              Priority
            %th
        - current_user.applications.each do |application|
          %tr.application-row{id:"application-row-#{application.id}"}
            %td= application.course.block.name
            %td= application.course.name
            %td
              - if application.priority == 1
                %strong
                  = application.priority
              - else
                = application.priority
            %td
              = link_to "Change", apply_path(current_user.course_batch, application.course.block), class: "btn btn-xs btn-primary"