config/routes.rb
Rails.application.routes.draw do

  get 'batches/:id/toggle' => 'batches#toggle', as: "batch_toggle"

  get 'apply/:batch/:block' => 'apply#block', as: "apply"
  get 'apply/:block/:application/up' => 'apply#up', as: "up"
  get 'apply/:block/:application/down' => 'apply#down', as: "down"
  get 'apply/summary', as: "summary"

  get 'public/index' => 'public#index'
  get 'public/students/idle' => 'public#idle_students', as: "idle_students"
  get 'public/applications/incomplete' => 'public#incomplete_applications', as: "incomplete_applications"
  get 'public/courses/available' => 'public#available_courses', as: "available_courses"
  get 'public/batches' => 'public#batches', as: "batches"
  get 'public/results' => 'public#results', as: "results"

  root to: 'public#index'

  devise_for :users, :skip => :registrations

  mount Upmin::Engine => '/admin'

  Upmin::Engine.routes.draw do
    resources :upload, only:[:create, :show]
    get "/downolad/applications" => "download#applications", as: "download_applications"
    get "/downolad/users" => "download#users", as: "download_users"
    get "/downolad/courses" => "download#courses", as: "download_courses"
    get "/upload/new/:type" => "upload#new", as: "new_upload"
  end

end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
%li= link_to 'Idle students', idle_students_path
%li= link_to 'Incomplete applications', incomplete_applications_path
%li= link_to 'Available courses', available_courses_path
%li= link_to 'Batches', batches_path
%li= link_to 'Results', results_path
- if user_signed_in?
  %li= link_to 'Admin', upmin_path if current_user.admin?
  %li= link_to 'Sign out', destroy_user_session_path, :method=>'delete'
- else
  %li= link_to 'Sign in', new_user_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Course Application'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Course Application'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield